version: "3"

services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/finance_master

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name

volumes:
  database_data:
