version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://user:password@localhost/finance_master

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_master
      POSTGRES_INITDB_ARGS: "--data-checksums"

volumes:
  database_data:
